### ISSUE TITLE
Tests: current + to-do's

### ISSUE THREAD

**Issue by victormasson21** [fac-17/Autsera#142]
### Tests

**App**
App renders without crashing
User journey from initial App render

**404**
The 404 Page renders

**RouterLink**
RouterLink renders

**HelpPage**
The Help Page renders
The Pause Button renders
The Play Button renders

**HomePage**
The HomePage should render
The HomePage should include the Buttons (both)
The HomePage should not include Continue buttons

**StartButton**
startButton is rendered
startButton calls the passed in onClick function

**MapPage**
The Map Page renders
MapPage includes a Go Back Button
MapPage includes a Playground Button
Places rendered on the map match places available on data
Locked places render with locked class
Click on locked place has no effect
**PlaceCircle**
if placeCircle renders when given a place
if placeCircle renders the text of the place correctly
if placeCircle renders the right link

**Stars**
if it renders stars
if it renders stars correct number of filled stars
if it renders stars correct number of empty stars
if it renders stars correct number of  stars

**PlacePage**
The Place Page renders
PlacePage has links to all interactions
Locked interactions render with locked class
**InteractionCircle**
The InteractionCircle renders
InteractionCircle includes the name of the interaction
InteractionCircle includes the link to the interaction

**InteractionPage**
The Interaction Page renders
Game starts from scratch when user re-enters page
Selecting an answer changes the class to 'selected'
Test if there is a back button with correct link'
Test if setCompleted gets called with the right argument
if clicking on answer gives the right response from avatar
if clicking on avatar gives the right hint

**Avatar**
Helper renders with the right text
Helper image appears when there is no speech provided
Helper component shows the helpText when clicked
if speechText and helpText both passed in -> helpText replaces speechText when helper is clicked
if speechText and helpText both passed in -> helpText stays visible after multiple clicks
speechText disappears after timeOut
helpText disappears after timeOut expires

### To be added / to do's
- [x] Rename tests for consistency / clarity throughout
- [x] MapPage > click on locked places has no effect
- [x] PlacePage > locked interactions get class "locked"
- [x] PlacePage > unlicked interactions get class "unlocked"
- [x] App > mock user journey from HomePage to completing first place
